---
# tasks file for building load balancer image
- name: Install prerequisites
  tags: [caddy]
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - debian-archive-keyring
      - gnupg2
    update_cache: yes
  retries: 5

- name: Import official Caddy GPG key
  tags: [caddy]
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present

- name: Add Caddy repository
  tags: [caddy]
  apt_repository:
    repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present

- name: Install Caddy
  tags: [caddy]
  apt:
    name: caddy
    update_cache: yes