---
# tasks file for load_balancer
- { import_tasks: build.yml, tags: [never,build], become: yes }

- name: Configure nginx for load balancing
  tags: [nginx]
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
