---
# tasks file for load_balancer
- { import_tasks: build.yml, tags: [never,build], become: yes }

- name: Configure Caddy for load balancing
  tags: [caddy]
  become: yes
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644
  notify: restart caddy

- name: Configure .ssh
  tags: [ssh]
  become: no
  copy:
    dest: ~/.ssh/config
    content: |
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        LogLevel=ERROR

- name: Configure tmux
  tags: [tmux]
  become: no
  copy:
    dest: ~/.tmux.conf
    content: |
      set -g prefix C-a
      set -g default-terminal "screen-256color"