---
# tasks file for building database image
- name: Configure Postgres database
  become: yes
  tags:
    - postgres
  block:
    - name: Ensure psycopg2 is installed and is latest version
      tags:
        - psycopg2
      apt:
        name: python3-psycopg2
        state: latest
