gen3:
  guppy:
    enabled: true
    indices:
      - index: gen3_subject
        type: subject
      - index: gen3_file
        type: file
    configIndex: gen3_array_config
    authFilterField: auth_resource_path
