global:
  dev: false
  postgres:
    dbCreate: true
    externalSecret: "gen3-db-creds"

gen3:
  fence:
    image:
      pullPolicy: IfNotPresent
    enabled: true

  guppy:
    enabled: false

  peregrine:
    enabled: false

  arborist:
    image:
      pullPolicy: IfNotPresent
    enabled: true
    dbRestore: false

  indexd:
    image:
      pullPolicy: IfNotPresent
    enabled: true
    dbRestore: false

  metadata:
    enabled: false

  sheepdog:
    enabled: false

  wts:
    enabled: false

  pidgin:
    enabled: false

  audit:
    enabled: false

  portal:
    image:
      pullPolicy: IfNotPresent
    enabled: true
