- name: Add gen3 helm repo
  command: bin/helm repo add gen3 https://helm.gen3.org
  args:
    chdir: /home/{{ gen3.user }}
  register: helm_repo_add_gen3
  changed_when: '"already exists" not in helm_repo_add_gen3.stdout'

- name: Update gen3 helm repos
  command: bin/helm repo update gen3
  args:
    chdir: /home/{{ gen3.user }}
  register: helm_repo_update

- name: Create/update values.yml
  tags: values
  template:
    src: values.yml
    dest: "~/values.yml"
    mode: 0600

#- name: Start gen3 helm
#  become: no
#  command: helm upgrade --install elwazirelease gen3/gen3 -f /home/{{ ansible_user }}/values.yml
