- name: Install helm
  vars:
    url: https://get.helm.sh/helm-v3.11.2-linux-amd64.tar.gz
    checksum: 'sha256:781d826daec584f9d50a01f0f7dadfd25a3312217a14aa2fbb85107b014ac8ca'
  block:
    - name: Download helm
      get_url:
        url: "{{ url }}"
        dest: "~/src/helm.tar.gz"
        checksum: "{{ checksum }}"
        mode: 0755
    - name: Create helm directory
      file:
        path: "~/helm"
        state: directory
        mode: 0755
    - name: Extract helm
      unarchive:
          src: "~/src/helm.tar.gz"
          dest: "~/helm"
          remote_src: true
          mode: 0755
          creates: "~/helm/linux-amd64/helm"
    - name: Copy helm to gen3 bin
      copy:
          src: "~/helm/linux-amd64/helm"
          dest: "~/bin/helm"
          mode: 0755
          remote_src: true

