- name: Check k9s version
  command: ~/bin/k9s version
  register: k9s_version
  failed_when: false
  changed_when: false

- name: Install k9s
  tags: k9s
  when: k9s_version.rc != 0 or 'v0.50.18' not in k9s_version.stdout
  block:
    - name: Download k9s
      get_url:
        url: https://github.com/derailed/k9s/releases/download/v0.50.18/k9s_Linux_amd64.tar.gz
        dest: ~/src/k9s.tar.gz

    - name: Extract k9s
      unarchive:
        src: ~/src/k9s.tar.gz
        dest: ~/bin
        remote_src: true
