---
# handlers file for database

- name: Restart postgres
  become: yes
  systemd:
    name: postgresql
    state: restarted

- name: Restart elasticsearch
  become: yes
  systemd:
    name: elasticsearch
    state: restarted

