---
# tasks file for configuring the docker host

- name: Ensure admin user is in docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    group: "docker"
    state: present

- name: clone gen3 commons docker compose-services
  git:
    repo: https://github.com/uc-cdis/compose-services.git
    dest: ~/compose-services
    update: no

- name: Run creds_setup.sh
  command: ./creds_setup.sh "{{ ansible_default_ipv4.address }}"
  args:
    chdir: ~/compose-services

- name: Update fence configuration
  block:
    - name: Update BASE_URL
      lineinfile:
        path: ~/compose-services/Secrets/fence-config.yaml
        regexp: '^BASE_URL: .*$'
        line: 'BASE_URL: https://{{ database_ip }}/user'
    - name: Update DB
      lineinfile:
        path: ~/compose-services/Secrets/fence-config.yaml
        regexp: '^DB: .*$'
        line: 'DB: postgresql://{{ postgres_fence_user }}:{{ postgres_fence_password }}@{{ database_ip }}:5432/fence_db'

## BASE_URL: 'https://192.168.10.236/user'
## DB: 'postgresql://fence_user:fence_pass@postgres:5432/fence_db'

- name: Remove all depends_on postgres
  lineinfile:
    path: ~/compose-services/docker-compose.yml
    regexp: '^ *- postgres$'
    state: absent


#- name: Add the docker-compose.override.yml.j2 template file to the compose-services directory
#  template:
#    file: docker-compose.override.yml.j2
#    dest: ~/compose-services/docker-compose.override.yml



#  template:
#    src: docker-compose.override.yml.j2
#    dest: ~/compose-services/docker-compose.yml


