---
# tasks file for docker
- name: Upgrade all existing packages
  tags: build
  become: yes
  apt:
    upgrade: full
    update-cache: yes
  register: apt_res
  retries: 3
  delay: 15
  until: apt_res is success

- name: Install required packages
  tags: build
  become: yes
  apt:
    update-cache: yes
  retries: 3
  delay: 15
  until: apt_res is success

- name: Clean up packages
  tags: build
  become: yes
  apt:
    autoclean: yes
    autoremove: yes