---
# tasks file for docker
- name: Upgrade all existing packages
  tags: build
  become: yes
  apt:
    upgrade: full
    update-cache: yes
  register: apt_res
  retries: 3
  delay: 15
  until: apt_res is success

- name: Install required packages
  tags: build
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update-cache: yes

- name: Add docker repo key
  tags: build
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get DEB architecture
  tags: build
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Add docker repository
  tags: build
  become: yes
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install docker
  tags: build
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update-cache: yes

- name: Clean up packages
  tags: build
  become: yes
  apt:
    autoclean: yes
    autoremove: yes