---
# tasks file for base

- name: Upgrade all existing packages
  apt:
    upgrade: dist
    update-cache: yes
    autoremove: yes
  register: apt_res
  retries: 3
  delay: 15
  until: apt_res is success
  become: yes